### ISSUE TITLE
Get by category

### ISSUE THREAD

**Issue by ghost** [arrizalamin/october-portfolio#19]
Great plugin!

Is it possible to list by category like how the tags work?  

So instead of the component with a category selected, is is possible to have that blank and the url /portfolio/category/catname and fetch all the items that are marked with that category?

**Comment by ghost** [comment]
Ok I added in  :selected_cat to defineProperties  and changed the function loadItemsByCategory to match the tags and now works.

**Comment by gluleci** [comment]
i add like this , but not working. how can you do this.

  $this->portfolio = Item::paginate($this->property('itemsPerPage'), $this->property('pageNumber'), $this->loadItemsByCategory($this->property('category')));
             $this->portfolio = Item::orderBy('order', $this->property('order'))->paginate($this->property('itemsPerPage'), $this->property('pageNumber'), $this->loadItemsByCategory($this->property('category')));
