### ISSUE TITLE
Able to have different layouts for the plugin?

### ISSUE THREAD

**Issue by andytan2624** [arrizalamin/october-portfolio#20]
This is a fantastic plugin

But i was wondering I have a htm file in /partials/portfolio/default.htm that has the default look of the portfolio plugin on my homepage. But I want to have the same plugin show up in a different page, but have a different layout, how can i achieve this (i.e. have a file called /partials/portfolio/anotherlayout.htm)

Is this possible and how can this be achieved?

**Comment by arrizalamin** [comment]
Yes, You need to make alias and put your layout in /partials/[alias]/default.htm
<img width="418" alt="screenshot at jan 31 17-31-09" src="https://cloud.githubusercontent.com/assets/3162413/12701598/7d373f1c-c840-11e5-9c32-6a246c87e644.png">

**Comment by joaocv3** [comment]
I think it should be in the documentation. It took me hours to figure this out.
