### ISSUE TITLE
Get tag name in page

### ISSUE THREAD

**Issue by vshepel** [arrizalamin/october-portfolio#21]
Hi!
How can I display the tag name (:selected_tag) on the page, not field URL? Example

![image](https://cloud.githubusercontent.com/assets/14239290/12799879/0e6e8e68-cada-11e5-8f15-6a0a049bf2a3.png)

**Comment by arrizalamin** [comment]
you can access url parameter by using this.param. e.g. {{ this.param.selected_tag }} if you're using :selected_tag parameter
