### ISSUE TITLE
Update plugin!

### ISSUE THREAD

**Issue by vshepel** [arrizalamin/october-portfolio#22]
Plugin not fully working! If you install it via the backend, there is no "item" component in the list (only Portfolio item):

![2016-02-05 01 01 48](https://cloud.githubusercontent.com/assets/14239290/12832677/20f086c0-cba4-11e5-976d-edc2858154b4.png)

I moved the files from the repository in folder "arrizalamin/portfolio", and in the list components appeared "Item", but it does not work, because an error occurs:

![2016-02-05 00 58 18](https://cloud.githubusercontent.com/assets/14239290/12832652/f74ba49e-cba3-11e5-8cad-2545cf72e664.png)

Please help me! Wonderful plugin, but I can not use it

**Comment by arrizalamin** [comment]
sorry my fault, I never checked all incoming PRs. please update to v1.4.2, close if you solved your problem.

**Comment by vshepel** [comment]
Everything is fine, thank you very much!
