### ISSUE TITLE
Plugin isn't recognised on the backend

### ISSUE THREAD

**Issue by damianlewis** [arrizalamin/october-portfolio#23]
I've added the plugin to my project account via the OctoberCMS website. When I check the backend for system updates, the plugin is listed as a 'New Plugin' in the 'Software Update' modal. When I 'Update Software' the plugin downloads and the backend notifies me that the update was successful but it isn't listed as one of the installed plugins. When I check for system updates again, the plugin is still listed as a 'New Plugin' that needs installing.

The plugin has downloaded, I can see it in the plugins directory but it seems that the backend doesn't recognise it.

**Comment by joaocv3** [comment]
I've had the same issue. I first thought it could be a octoberCMS's issue but any other plugin is installing/working properly.

**Comment by arrizalamin** [comment]
sorry, please update to v1.4.2
