### ISSUE TITLE
Sorting order on Items page

### ISSUE THREAD

**Issue by sliderweb** [arrizalamin/october-portfolio#27]
On items page sort ordering not working. Always ordered by ID (asc). Help me to understand sorting code.

**Comment by arrizalamin** [comment]
Items always ordered by ID, but you can change the order to Ascending/Descending in the Portfolio List component
<img width="416" alt="screen shot 2016-07-18 at 12 55 27 pm" src="https://cloud.githubusercontent.com/assets/3162413/16906770/f0701230-4ce6-11e6-8d55-baac94972959.png">
