### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by ujackson** [arrizalamin/october-portfolio#33]
Thanks for this beautiful plugin. I noticed the pagination feature doesn't work as it does nothing when you click on the pagination links. Any pointers on how to fix this?
Thanks.

**Comment by arrizalamin** [comment]
add `/:page?` after your page url like this
<img width="787" alt="screen shot 2016-07-18 at 1 02 50 pm" src="https://cloud.githubusercontent.com/assets/3162413/16906854/1603511e-4ce8-11e6-87ff-2f903957f8a0.png">
