### ISSUE TITLE
Javascript error: $(...).tagbox is not a function

### ISSUE THREAD

**Issue by pavlo-tk** [arrizalamin/october-portfolio#34]
Hello. Thank you for the so usable plugin.

I'm using OctoberCMS build 345 and Portfolio plugin v. 1.4.2.
On the create item page there is a javascript error: `$(...).tagbox is not a function` at `/plugins/arrizalamin/portfolio/vendor/owl/tagbox/widget/partials/_widget.htm:26`

![sc-007](https://cloud.githubusercontent.com/assets/7204866/15986660/bd721ec0-3015-11e6-9508-708b60fd10f0.jpg)

**Comment by arrizalamin** [comment]
I guess [tagbox.js](https://github.com/october-widgets/tagbox) not loaded, try view-source the page and search `plugins/arrizalamin/portfolio/vendor/owl/tagbox/widget/assets/js/tagbox.js`. if it's not there, reinstall the plugin or run `composer install` from plugin directory.

**Comment by pavlo-tk** [comment]
Oh, I got the problem: I'm using separate public directory and tagbox with all it's assets are not mirrored to the public folder.
Take a look at the documentation: https://octobercms.com/docs/setup/configuration#public-folder
Can you fix this, make mirroring be aware of the vendor assets? I don't really familiar with this now, how to set it up.

**Comment by arrizalamin** [comment]
well, mirroring public folder still experimental and october has not provided a way to [define assets folder](https://github.com/octobercms/october/issues/1644) yet. ~~I think [changing vendor directory](https://getcomposer.org/doc/06-config.md#vendor-dir) to "assets" would work.~~ Nope, october only looks for [vendor directory](https://github.com/octobercms/october/blob/master/modules/system/classes/PluginManager.php#L191).

**Comment by pavlo-tk** [comment]
Thank you very much!
