### ISSUE TITLE
Page Title

### ISSUE THREAD

**Issue by Michael-Reich** [arrizalamin/october-portfolio#36]
Is it possible to make the page Title the active item?

Something like this?

```
function onEnd()
{
    if ($this['item'])
        $this->page->title = $this['item']->title;
}
```

**Comment by arrizalamin** [comment]
``` php
function onEnd()
{
    if ($this['item']) {
        $this->page->title = $this['item']->item->title;
    }
}
```

**Comment by Inklementia** [comment]
function onEnd()
{
    $_item = $this->components['item'];

    if ($_item->item) {
        $this->page->title = $_item->item->title;
    }else {
        return Redirect::to($this->pageUrl('404'));
    }
}
