### ISSUE TITLE
Customize code

### ISSUE THREAD

**Issue by polikin** [arrizalamin/october-portfolio#4]
It is possible to have to different html for the component? I mean, one html for each category.

It is possible to overwrite the defautl html?

**Comment by arrizalamin** [comment]
you can override component from your partials [https://octobercms.com/docs/cms/components#customizing-default-markup](https://octobercms.com/docs/cms/components#customizing-default-markup)

**Comment by polikin** [comment]
I tried this:

`themes/xxx/partials/foo.htm`

I copied `% for item in __SELF__.portfolio %} ...` into foo.htm
I replaced `__SELF__.portfolio` by `foo.portfolio`
in my layout, I put `{% partial 'foo' %}` with the component Portfolio (alias: foo). Is that correct?

**Comment by arrizalamin** [comment]
that you just did is not override the component
in you're not overriding the component, you should add that component to your partials like this

```
[portfolio foo]
category = "3"
==
{% for item in foo.portfolio %}
    <h2>{{ item.title }}</h2>
    <div>
        {{ item.description|raw }}
    </div>
{% endfor %}
```

if you want to override the component, you should copy default markup to partials/portfolio/default.htm without replacing `__SELF__`

**Comment by polikin** [comment]
alright, thanks!
