### ISSUE TITLE
Add summary field

### ISSUE THREAD

**Issue by polikin** [arrizalamin/october-portfolio#5]
It is possible to add an Summary field?

**Comment by arrizalamin** [comment]
summary like excerpt?

**Comment by polikin** [comment]
like Description

**Comment by arrizalamin** [comment]
so whats the different with existing description field?

**Comment by polikin** [comment]
The user can write a summary for his item (ex: thumbnail) and he can write a full description for the item details. It will be nice if we can have a short and long description.

**Comment by arrizalamin** [comment]
I think that's optional, you can extend the plugin by follow thishttps://vimeo.com/108040919
