### ISSUE TITLE
Thumbnail bug?

### ISSUE THREAD

**Issue by acwoss** [arrizalamin/october-portfolio#8]
When I use the code below as partial of the component, the plugin works correctly. However, when I try to generate the Thumbnail from the image, using `{{ item.images[0].thumb(300, { extension: 'png' }) }}` instead of  `{{ item.images[0].path }}`, layout of the page is not loaded, as shown in the images below. You have no idea why this happens?

``` html
{% for item in __SELF__.portfolio %}
<div class="project-post {{ item.category.name|lower|replace({' ': '-'}) }}">
  <img src="{{ item.images[0].path }}" alt="{{ item.images[0].title }}">
  <div class="hover-box">
    <a class="link" href="{{ 'project'|page({project_id: item.id, slug: item.title|slug }) }}">Visualizar</a>
  </div>
</div>
{% endfor %}
```

Using the path attr, the plugins works perfect: 

![untitled-2](https://cloud.githubusercontent.com/assets/597817/9607406/5ca1303c-509f-11e5-9c2b-c31214561ca0.png)

Using the thumbnail, only the code of page is loaded, with no layout:

![untitled-3](https://cloud.githubusercontent.com/assets/597817/9607458/9e12c292-509f-11e5-9aff-7dd7a8ade647.png)

**Comment by arrizalamin** [comment]
I don't know what happen. I tried using demo theme, it works
<img width="569" alt="screenshot at sep 06 11-38-09" src="https://cloud.githubusercontent.com/assets/3162413/9702539/cf39bb10-548b-11e5-8607-5dd65f7ff16c.png">
